# Generated by Django 3.2.16 on 2024-03-05 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('party', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('company', models.CharField(default='YOUR COMPANY', max_length=256)),
                ('accounting_year', models.IntegerField(blank=True, default=0, null=True)),
                ('invoice_sequence', models.IntegerField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('marketplace', models.CharField(blank=True, choices=[('1mg', 'One Mg'), ('Amazon', 'Amazon'), ('BigBasket', 'Big Basket'), ('Flipkart', 'Flipkart'), ('Meesho Offline', 'Meesho'), ('MenXP', 'Menxp'), ('MyUpchar', 'My Upchar'), ('PayTM', 'Paytm'), ('Pharmeasy', 'Pharmeasy'), ('Purplle', 'Purplle'), ('Shopify', 'Shopify'), ('Shopify_2', 'Shopify 2'), ('Snapdeal', 'Snapdeal'), ('Cred', 'Cred'), ('Shykart', 'Shykart'), ('Aayu Chemist', 'Aayu Chemist')], max_length=50, null=True)),
                ('invoice_type', models.CharField(blank=True, choices=[('MJB2B', 'B2B Tax Invoice'), ('MJST', 'Stock Transfer'), ('MJDC', 'Delivery Challan'), ('MJINV', 'Tax Invoice'), ('MJCN', 'Credit Note'), ('MJDN', 'Debit Note'), ('MJ', 'Proforma Invoice'), ('MJSAM', 'Sample'), ('MJPO', 'Purchase Order'), ('MJPR', 'Payment Receipt')], max_length=50, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('transport_mode', models.CharField(blank=True, choices=[('Road', 'Road'), ('Air', 'Air')], max_length=25, null=True)),
                ('mode_of_payment', models.CharField(blank=True, choices=[('Cod', 'Cod'), ('Prepaid', 'Prepaid'), ('Credit', 'Credit')], max_length=25, null=True)),
                ('place_of_supply', models.CharField(blank=True, max_length=50, null=True)),
                ('city_of_supply', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_total', models.IntegerField(blank=True, default=0, null=True)),
                ('eway_bill', models.URLField(blank=True, max_length=256, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('Draft', 'Draft'), ('Processed', 'Processed'), ('Accepted for Fulfilment', 'Accepted'), ('In Transit', 'In Transit'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Returned', 'Returned')], max_length=50, null=True)),
                ('awb_number', models.IntegerField(blank=True, null=True)),
                ('courier_partner', models.CharField(blank=True, max_length=50, null=True)),
                ('aw_vw', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_pdf_url', models.URLField(blank=True, max_length=256, null=True)),
                ('e_invoice_url', models.URLField(blank=True, max_length=256, null=True)),
                ('box_label_url', models.URLField(blank=True, max_length=256, null=True)),
                ('ewb_number', models.BigIntegerField(blank=True, default=0, null=True)),
                ('irn', models.CharField(blank=True, max_length=256, null=True)),
                ('transport_id', models.CharField(blank=True, max_length=50, null=True)),
                ('transport_name', models.CharField(blank=True, max_length=50, null=True)),
                ('transport_vehicle', models.CharField(blank=True, max_length=50, null=True)),
                ('bill_to_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_to_invoices', to='party.partydetails')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_to_invoices', to='party.partydetails')),
                ('ship_to_party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ship_to_invoices', to='party.partydetails')),
            ],
            options={
                'verbose_name_plural': 'Invoices',
                'ordering': ('-invoice_date', '-appointment_date'),
            },
        ),
        migrations.CreateModel(
            name='InvoiceProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('po', models.CharField(blank=True, max_length=30, null=True)),
                ('po_date', models.DateField(blank=True, null=True)),
                ('discount_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mrp', models.IntegerField(blank=True, null=True)),
                ('gst_percent', models.IntegerField(blank=True, null=True)),
                ('hsn_code', models.IntegerField(blank=True, null=True)),
                ('tax_type', models.CharField(blank=True, choices=[('igst', 'Igst'), ('cgst+sgst', 'Combined')], max_length=30, null=True)),
                ('igst', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('cgst', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('sgst', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('taxable_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('net_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
                ('box_qty', models.IntegerField(blank=True, null=True)),
                ('box_contents', models.CharField(blank=True, max_length=256, null=True)),
                ('box_no', models.IntegerField(blank=True, null=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_details', to='invoice.invoicedetails')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_detail', to='products.productmaster')),
            ],
            options={
                'verbose_name_plural': 'Invoice Products Details',
            },
        ),
    ]
