# Generated by Django 3.2.16 on 2024-03-05 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('product_name', models.CharField(blank=True, max_length=256, null=True)),
                ('mrp', models.IntegerField(blank=True, null=True)),
                ('hsn_code', models.IntegerField(blank=True, null=True)),
                ('gst_percent', models.IntegerField(blank=True, null=True)),
                ('primary_box_qty', models.IntegerField(blank=True, null=True)),
                ('pack', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Products',
            },
        ),
    ]
